name: Notify on PR Opened

on:
  pull_request:
    types: [opened]

jobs:
  notify_on_pr_opened:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        uses: slack/notify@v3
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_CHANNEL: general  
          SLACK_MESSAGE: |
            Nuevo Pull Request abierto (#${{ github.event.pull_request.number }}):
            - Título: ${{ github.event.pull_request.title }}
            - Autor: ${{ github.event.pull_request.user.login }}
            - URL: ${{ github.event.pull_request.html_url }}
