name: PR Yml

on:
  push:
    branches:
       - main
  pull_request:
    types: [opened]

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord notification
        if: github.event_name == 'push'
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: https://discord.com/api/webhooks/1262462826539126825/Wmf6s7_MLl_qinTIK7pcOThEigAi0ZUB85wDKHJVy_u1rjzkAscIocfr6Xu45_XZvWbJ
          username: 'PR Github Actions -  Bot'
          content: |
            New Pull Request Open! :
               Title: ${{ github.event.pull_request.title }}
               Description: ${{ github.event.pull_request.body }}
               Created By: ${{ github.event.pull_request.user.login }}
               Source Branch: ${{ github.event.pull_request.head.ref }}
               Target Branch: ${{ github.event.pull_request.base.ref }}
            Pull Request URL: ${{ github.event.pull_request.html_url }}
