name: Demo yml
on:
  push

jobs:
  notify_on_pr_opened:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        uses: rtCamp/action-slack-notify@v2
        env:
          slack_webhook: ${{ secrets.WEBHOOK_URL }}
          slack_message: |
            Nuevo Pull Request abierto 
