name: Run Echo Commands

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - develop
      - master

jobs:
  echo-commands:
    runs-on: ubuntu-latest
    
    steps:
      # Paso 1: Echo "Hola Mundo"
      - name: Echo Hola Mundo
        run: echo "Hola Mundo"
      
      # Paso 2: Echo "Morrowind"
      - name: Echo Morrowind
        run: echo "Morrowind"
        
    # Solo ejecutará si el PR ha sido aprobado
    if: github.event.pull_request.review.state == 'approved'
