name: Demo Yml

on:
  push

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK}}    
          SLACK_MESSAGE: |
            Nuevo Pull Request abierto 
