name: Demo Pr

on:
  pull_request:
    types: [opened]

jobs:
  Demo_yml:
    runs-on: ubuntu-latest
    steps:
      - name: Echo message
        run: echo "Este es un mensaje de prueba para un Pull Request"
